"""1.1.0

Revision ID: 720a6289a697
Revises: None
Create Date: 2023-01-22 08:18:00.723780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720a6289a697'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1.0.0
    op.execute('DROP TABLE IF EXISTS IGNORED_WORDS')
    op.execute('DROP TABLE IF EXISTS REPLACED_WORDS')
    op.execute('DROP TABLE IF EXISTS OFFSET_WORDS')
    try:
        with op.batch_alter_table("CUSTOM_WORDS") as batch_op:
            batch_op.alter_column('OFFSET', type_=sa.Text, existing_type=sa.Integer)
    except Exception as e:
        print(str(e))
    # 1.0.3
    try:
        with op.batch_alter_table("TRANSFER_HISTORY") as batch_op:
            batch_op.alter_column('FILE_PATH', new_column_name="SOURCE_PATH", existing_type=sa.Text)
            batch_op.alter_column('FILE_NAME', new_column_name="SOURCE_FILENAME", existing_type=sa.Text)
            batch_op.alter_column('SE', new_column_name="SEASON_EPISODE", existing_type=sa.Text)
            batch_op.add_column(sa.Column('TMDBID', sa.Integer))
            batch_op.add_column(sa.Column('DEST_PATH', sa.Text))
            batch_op.add_column(sa.Column('DEST_FILENAME', sa.Text))
    except Exception as e:
        print(str(e))
    # 1.0.7
    try:
        with op.batch_alter_table("TRANSFER_UNKNOWN") as batch_op:
            batch_op.add_column(sa.Column('MODE', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
